name: Generate Github-Pages

on:
  push:
    branches: [ fexo ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Run Export
        run: |
          export TZ='Asia/Shanghai'
          npm install
          hexo generate
      - name: Deploy Github-Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public

      - name: Refresh CDN
        run: npm run deploy:refresh-cdn
        env:
          CDN_ID: ${{ secrets.CDN_ID }}
          CDN_KEY: ${{ secrets.CDN_KEY }}
